### ISSUE TITLE
Contract for Remote Work

### ISSUE THREAD

**Issue by ghost** [nelsonic/remote-working-experiment#18]
Hi! I am working remotely (reviewing dwyl code and learning materials) and i need/would love to have a contract for my work so that I can be paid. Who do I need to speak to?

**Comment by ghost** [comment]
@edwardcodes I understand it was @nelsonic who commissioned you - please could you forward me an email of the details of the informal agreement you had with @nelsonic to mark(at)dwyl.io? I can make you a contract then.

**Comment by iteles** [comment]
@markwilliamfirth This was a verbal agreement for a one-off piece of work. Let's get the details from @nelsonic so we can pay the invoice.

**Comment by nelsonic** [comment]
The agreement was **€400**/month to _apprentice_ with dwyl remotely. 
(_it's not "one off" the idea is that Eduardo can be a member of our team once he is up-to-scratch on all the tech/tools. This is phenomenal value for dwyl considering he his existing skills in networking and IT administration_)
The _initial_ task is to review (_and improve_) our learning materials for the dwyl technology stack 
so that we can ensure that _new joiner_ on-boarding is as smooth as possible.

**Comment by iteles** [comment]
That wasn't clear, my apologies - I meant a one-off *invoice* for now rather than a one-off piece of work 👍

**Comment by ghost** [comment]
Hi! @markwilliamfirth Do you think it´s possible we resolve this problem today? It would help me a lot!
Thanks.

**Comment by ghost** [comment]
@edwardcodes please can you send me an email to mark(at)dwyl.com with your:

- Full legal name
- Home address
- The date you started working on the project

Once we have this information I can generate your contract and we can set up the invoice and pay you https://github.com/dwyl/hq/issues/322

**Comment by ghost** [comment]
@markwilliamfirth done, thank you! (waiting for this to be complete to close this issue)

**Comment by ghost** [comment]
@nelsonic please can you confirm the hours per week / month? Is it standard 40h/week with a start date of 13 April 2017?

**Comment by ghost** [comment]
@nelsonic please can you confirm the role - "Learning Materials Writer"?

**Comment by iteles** [comment]
@markwilliamfirth "Learning Materials Reviewer" 👍

**Comment by nelsonic** [comment]
Reviewer (_for now and eventual writer_)

**Comment by ghost** [comment]
Thanks! also previous comment (https://github.com/dwyl/remote-working/issues/18#issuecomment-303038235) @nelsonic 

(Hours per week and start date)

**Comment by nelsonic** [comment]
@markwilliamfirth yeah, hours-per-week should be _around_ 40h (_dependent on progression rate_)
but "_officially_" this sounds fine.
And start date 13th April is good. 
Thanks! 🎉

**Comment by ghost** [comment]
@edwardcodes I've sent you your contract!

**Comment by ghost** [comment]
@markwilliamfirth Done, Thank you!!

**Comment by ghost** [comment]
Completed and uploaded to Charlie; invoice paid 👍
