### ISSUE TITLE
The productivity pitfalls of working from home in the age of COVID-19

### ISSUE THREAD

**Issue by iteles** [nelsonic/remote-working-experiment#36]
https://news.stanford.edu/2020/03/30/productivity-pitfalls-working-home-age-covid-19/

> The global work-from-home movement intended to maintain output and efficiency during the COVID-19 pandemic could actually generate a worldwide productivity slump and threaten economic growth for many years, says Stanford economist Nicholas Bloom.

In reality, what this article is saying is that this is due to working from home suddenly without an adequate environment, an ill-prepared employer and no transition period (in-home + in-office days). The article itself references a 2015 study where Nicholas Bloom shows the benefits and "increased productivity" of working from home.

**Comment by imanishbarnwal** [comment]
Hello, @iteles can explain more about this issue. I am new to this opensource community and I want to go for this issue. Thank You!!

**Comment by iteles** [comment]
Hi @imanishbarnwal , thanks for being so enthusiastic! 
When I first opened it, I felt it might be a useful counterpoint article that could be added to a further reading list. However, having read it again, it speaks of a very specific set of circumstances that might not be useful overall.

Thanks for raising the lack of clarity with me, I will close this issue for now!

Please take a look at our https://github.com/dwyl/start-here/ repo and feel free to open issues there with improvements that can be made! ☺️

**Comment by imanishbarnwal** [comment]
> Hi @imanishbarnwal , thanks for being so enthusiastic!
> When I first opened it, I felt it might be a useful counterpoint article that could be added to a further reading list. However, having read it again, it speaks of a very specific set of circumstances that might not be useful overall.
> 
> Thanks for raising the lack of clarity with me, I will close this issue for now!
> 
> Please take a look at our https://github.com/dwyl/start-here/ repo and feel free to open issues there with improvements that can be made! ☺️

Cool. Thanks for responding 😃
